# Generated by Django 4.0.4 on 2022-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('WATER', 'Water'), ('GRASS', 'Grass'), ('GHOST', 'Ghost'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=30)),
                ('hp', models.PositiveIntegerField()),
                ('active', models.BooleanField(verbose_name=True)),
                ('name_fr', models.CharField(default='', max_length=30)),
                ('name_ar', models.CharField(default='', max_length=30)),
                ('name_jp', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
