# Generated by Django 4.0.4 on 2022-10-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('WA', 'Water'), ('GR', 'Grass'), ('GH', 'Ghost'), ('ST', 'Steel'), ('FA', 'Fairy')], max_length=30),
        ),
    ]
