# Generated by Django 4.0.4 on 2022-10-16 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_alter_pokemon_name_ar_alter_pokemon_name_fr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50, 'cant be below 50'), django.core.validators.MaxValueValidator(350, "can't be a above 350")]),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('WA', 'Water'), ('GR', 'Grass'), ('GH', 'Ghost'), ('ST', 'Steel'), ('FA', 'Fairy')], max_length=2),
        ),
    ]
